### PR TITLE
Updating the css to fix the Mobile view

### LINKED ISSUE #37: Dentistry header issue on mobile
There is a small problem with the dentistry header on mobile:
image

@bosschaert @sdmcraft @meejain

### PR DESCRIPTION
**Pull request by meejain**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fixes #37 

Test URLs:
- Original: https://www.sunstar-foundation.org/dentistry/concept
- Before: https://main--sunstar-foundation--sunstar-foundation.hlx.page/dentistry/concept
- After: https://issue37--sunstar-foundation--sunstar-foundation.hlx.page/dentistry/concept

- [ ] New Blocks introduced in this PR
      If yes, please provide details below

Block Name    | Documentation
------------- | -------------
 For e.g. cards | [doc-link](https://main--sunstar-foundation--sunstar-foundation.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/cards&index=0)

- [ ] New variations introduced in this PR

Variation Name    | Documentation
------------- | -------------
 For e.g. cards (grid)  | [doc-link](https://main--sunstar-foundation--sunstar-foundation.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/cards&index=2)

### CODE REVIEW

**Review by ehrro — CHANGES_REQUESTED** [review]
Hello @meejain,

On smaller screens it still not good.

image

Can you please update the font size for mobile to --heading-font-size-xs ?

image

Thank you.

**Comment by meejain** [comment]
> Hello @meejain,
> 
> On smaller screens it still not good.
> 
> image
> 
> Can you please update the font size for mobile to --heading-font-size-xs ?
> 
> image
> 
> Thank you.

Hello @ehrro  - Pl check now - 

https://issue37--sunstar-foundation--sunstar-foundation.hlx.page/dentistry/concept

image

**Review by ehrro — CHANGES_REQUESTED** [review]
There is still a small issue when the nav is opened:

image

**Comment by meejain** [comment]
> There is still a small issue when the nav is opened:
> 
> image

Please check now - https://issue37--sunstar-foundation--sunstar-foundation.hlx.page/dentistry/concept

image

**Review by ehrro — APPROVED** [review]

**Pull request merged**
