### PR TITLE
issues-8 Fixed the Dentistry Header

### LINKED ISSUE #8: Dentistry Header revamp
Can you please enhance the dentistry site header?

1. The text next to the logo should be font-weight: normal, should have 32px (2rem) distance from the logo and should be standard blue color (same as the logo).
2. The text above the phone number should be smaller, should be standard blue color and should be positioned on top of the phone number (4px from the phone number).
3. The phone number should be in standard blue color.
4. The buttons should be 24px(1.5rem) from the phone number and the text size should be a bit smaller.

image

Not a blocker

@bosschaert @sdmcraft

### PR DESCRIPTION
**Pull request by shrotia**
Fixes #8

Test URLs:
- Original: https://www.sunstar-foundation.org/dentistry
- Before: https://main--sunstar-foundation--sunstar-foundation.hlx.live/dentistry
- After: https://issue-8-v2--sunstar-foundation--sunstar-foundation.hlx.live/dentistry

### CODE REVIEW

**Comment by shrotia** [comment]
After the Changes:

Desktop:
image

Tablet:
image

Mobile:
image

CC: @ehrro

**Comment by shrotia** [comment]
@RitwikSrivastava @meejain  Please have a look at the change, we do not need the nav-top section at the dentistry nav. But removing it would be a bigger change, hence positioned it through css. Please have a look and confirm if the changes looks aligned.

test url: https://issue-8-v2--sunstar-foundation--sunstar-foundation.hlx.live/dentistry

image

**Review by RitwikSrivastava — CHANGES_REQUESTED** [review]
> @RitwikSrivastava @meejain Please have a look at the change, we do not need the nav-top section at the dentistry nav. But removing it would be a bigger change, hence positioned it through css. Please have a look and confirm if the changes looks aligned.


Agree that removing the nav-top might result in other issues. 
But we also need to make sure that the changes doesn't affect the normal header. 
please see header at https://issue-8-v2--sunstar-foundation--sunstar-foundation.hlx.live/  .
the nav-top is hidden in normal header and font size is also impacting.

**Comment by shrotia** [comment]
> > @RitwikSrivastava @meejain Please have a look at the change, we do not need the nav-top section at the dentistry nav. But removing it would be a bigger change, hence positioned it through css. Please have a look and confirm if the changes looks aligned.
> 
> Agree that removing the nav-top might result in other issues. But we also need to make sure that the changes doesn't affect the normal header. please see header at https://issue-8-v2--sunstar-foundation--sunstar-foundation.hlx.live/ . the nav-top is hidden in normal header and font size is also impacting.

@RitwikSrivastava The branch` issue-8-v2` is a temporary one. It's specifically for the dentistry header, which includes changes made to the `dentistrynav.docx` file (path: `/_drafts/shroti/dentistrynav`). [0]

For other pages that aren't related to dentistry, please refer the other branch `issue-8-v1`, which is the one this PR is based on. [1]

[0] https://issue-8-v2--sunstar-foundation--sunstar-foundation.hlx.live/dentistry
[1] https://issue-8-v1--sunstar-foundation--sunstar-foundation.hlx.live/

**Review by RitwikSrivastava — APPROVED** [review]

**Pull request merged**
