### PR TITLE
CLS issue in header for Mobile view

### PR DESCRIPTION
**Pull request by jindaliiita**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fixes #<gh-issue-id>

Test URLs:
- Original: https://www.sunstar-foundation.org/dentistry
- Before: https://main--sunstar-foundation--sunstar-foundation.hlx.live/dentistry
- After: https://cls-issue--sunstar-foundation--sunstar-foundation.hlx.live/dentistry

- [ ] New Blocks introduced in this PR
      If yes, please provide details below

Block Name    | Documentation
------------- | -------------
 For e.g. cards | [doc-link](https://main--sunstar-foundation--sunstar-foundation.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/cards&index=0)

- [ ] New variations introduced in this PR

Variation Name    | Documentation
------------- | -------------
 For e.g. cards (grid)  | [doc-link](https://main--sunstar-foundation--sunstar-foundation.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/cards&index=2)

### CODE REVIEW

**Comment by JiangLong2019** [comment]
@jindaliiita Except dentistry page, the memu bar disappears in the normal page such as [top page](https://cls-issue--sunstar-foundation--sunstar-foundation.hlx.live/). The class of memu bar is `nav-bottom` instead of `nav-bottom-parent` on these pages, it would be good to keep the bar on the top when scroll the page.

image

**Comment by jindaliiita** [comment]
> @jindaliiita Except dentistry page, the memu bar disappears in the normal page such as [top page](https://cls-issue--sunstar-foundation--sunstar-foundation.hlx.live/). The class of memu bar is `nav-bottom` instead of `nav-bottom-parent` on these pages, it would be good to keep the bar on the top when scroll the page.
> 
> image

Thanks @JiangLong2019 for the feedback. It's a good catch. I have now handled this case also

**Comment by sdmcraft** [comment]
@jindaliiita , I see the jerk in desktop as well. I think it should be fixed there as well.

https://github.com/user-attachments/assets/96df561b-e095-4dd8-954d-e761c2b4bb87

**Comment by jindaliiita** [comment]
@sdmcraft and @JiangLong2019 Can you please review it again

**Comment by JiangLong2019** [comment]
Thanks @jindaliiita, I checked both JP and EN pages, they work well.

**Review by sdmcraft — APPROVED** [review]

**Review by JiangLong2019 — APPROVED** [review]

**Pull request merged**
